# Generated by Django 5.2.1 on 2026-04-03 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subZone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.subzone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.zone')),
            ],
        ),
        migrations.CreateModel(
            name='FrontOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Huissier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subZone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.subzone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.zone')),
            ],
        ),
    ]
