# Generated by Django 5.2.1 on 2026-04-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialadvisor',
            name='subZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.subzone'),
        ),
        migrations.AlterField(
            model_name='financialadvisor',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.zone'),
        ),
        migrations.AlterField(
            model_name='frontoffice',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.zone'),
        ),
        migrations.AlterField(
            model_name='huissier',
            name='subZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.subzone'),
        ),
        migrations.AlterField(
            model_name='huissier',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.zone'),
        ),
    ]
