# Generated by Django 5.2.1 on 2026-03-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_scoreuser_groups_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialadvisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.scoreuser'),
        ),
        migrations.AlterField(
            model_name='frontoffice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.scoreuser'),
        ),
        migrations.AlterField(
            model_name='huissier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.scoreuser'),
        ),
    ]
