# Generated by Django 5.2.1 on 2026-04-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_financialadvisor_subzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialadvisor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialadvisor',
            name='npi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialadvisor',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialadvisor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='financials/'),
        ),
        migrations.AddField(
            model_name='frontoffice',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='frontoffice',
            name='npi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frontoffice',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='huissier',
            name='npi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='huissier',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='huissier',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='huissiers/'),
        ),
    ]
