# Generated by Django 5.2.1 on 2026-04-21 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_subscription_is_blocked_subscription_starts_at_and_more'),
        ('staff', '0003_financialadvisor_name_financialadvisor_npi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialadvisor',
            name='subZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_advisors', to='geography.subzone'),
        ),
        migrations.AlterField(
            model_name='financialadvisor',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_advisors', to='geography.zone'),
        ),
        migrations.AlterField(
            model_name='frontoffice',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontoffices', to='geography.zone'),
        ),
        migrations.AlterField(
            model_name='huissier',
            name='subZone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huissiers', to='geography.subzone'),
        ),
        migrations.AlterField(
            model_name='huissier',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huissiers', to='geography.zone'),
        ),
    ]
