# Generated by Django 5.2.1 on 2026-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_financialadvisor_subzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huissier',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
