# Generated by Django 5.2.1 on 2026-03-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
