# Generated by Django 5.2.1 on 2026-03-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_scoreuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='scoreuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='scoreuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='accountcredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.scoreuser'),
        ),
    ]
