# Generated by Django 5.2.1 on 2026-03-31 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_scoreuser_groups_and_more'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.scoreuser'),
        ),
    ]
