# Generated by Django 5.2.1 on 2026-04-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subzone',
            name='country',
        ),
    ]
