# Generated by Django 5.2.1 on 2026-04-06 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_remove_subzone_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='subzone',
            options={'verbose_name': 'Sous-zone', 'verbose_name_plural': 'Sous-zones'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='country',
            name='licence_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_in', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='geography.country')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
