# Generated by Django 5.2.1 on 2026-04-08 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Dette', 'verbose_name_plural': 'Dettes'},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'verbose_name': 'Remboursement', 'verbose_name_plural': 'Remboursements'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zubZone',
            new_name='subZone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
