# Generated by Django 5.2.1 on 2026-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_consultationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='validation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='validation_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='validation_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='validation_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
