# Generated by Django 5.2.1 on 2026-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_debt_validation_token_debt_validation_token_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='verified',
        ),
        migrations.AddField(
            model_name='debt',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée par le client'), ('rejected', 'Refusée par le client')], default='pending', max_length=10, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validé par le client'), ('rejected', 'Refusé par le client')], default='pending', max_length=10, verbose_name='Statut de validation'),
        ),
    ]
