# Generated by Django 5.2.1 on 2026-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_debt_verified_remove_repayment_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_monitored',
            field=models.BooleanField(default=False, verbose_name='Suivi activé'),
        ),
        migrations.AddField(
            model_name='debt',
            name='last_alert_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière alerte envoyée'),
        ),
    ]
