# Generated by Django 5.2.1 on 2026-04-20 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_debt_is_monitored_debt_last_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
