# Generated by Django 5.2.1 on 2026-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_debt_uuid_repayment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant remboursé lors de ce versement', max_digits=12),
            preserve_default=False,
        ),
    ]
