# Generated by Django 5.2.1 on 2026-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_phone_number'),
        ('staff', '0005_huissier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='is_monitored',
        ),
        migrations.AddField(
            model_name='debt',
            name='monitored_by',
            field=models.ManyToManyField(blank=True, related_name='monitored_debts', to='staff.huissier', verbose_name='Suivie par'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validé par le créditeur'), ('rejected', 'Refusé par le créditeur')], default='pending', max_length=10, verbose_name='Statut de validation'),
        ),
    ]
