"""
Django settings for score project.
Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path
from datetime import timedelta
import environ

# ─────────────────────────────────────────────
# ENVIRONNEMENT
# ─────────────────────────────────────────────

env = environ.Env(
    EMAIL_HOST_PASSWORD=(str, ""),
    FRONTEND_URL=(str, "http://localhost:3000"),
)

BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# ─────────────────────────────────────────────
# SÉCURITÉ
# ─────────────────────────────────────────────

SECRET_KEY = 'django-insecure-p(31*$-(60m=09woo$awze2(w4n8b5mx_a0)dc+7@rs^d*61vt'

DEBUG = True

ALLOWED_HOSTS = ['*']


# ─────────────────────────────────────────────
# APPLICATIONS
# ─────────────────────────────────────────────

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps projet
    'accounts',
    'staff',
    'geography',
    'customers',
    'dashboard',

    # Packages tiers
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'django_celery_beat',
]


# ─────────────────────────────────────────────
# MODÈLE UTILISATEUR PERSONNALISÉ
# ─────────────────────────────────────────────

AUTH_USER_MODEL = 'accounts.ScoreUser'


# ─────────────────────────────────────────────
# MIDDLEWARE
# ─────────────────────────────────────────────

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # désactivé volontairement (API)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'score.middleware.SubscriptionMiddleware',
]

ROOT_URLCONF = 'score.urls'

WSGI_APPLICATION = 'score.wsgi.application'


# ─────────────────────────────────────────────
# TEMPLATES
# ─────────────────────────────────────────────

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ─────────────────────────────────────────────
# CORS
# ─────────────────────────────────────────────

CORS_ALLOW_ALL_ORIGINS = True


# ─────────────────────────────────────────────
# BASE DE DONNÉES
# ─────────────────────────────────────────────

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ─────────────────────────────────────────────
# VALIDATION DES MOTS DE PASSE
# ─────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ─────────────────────────────────────────────
# INTERNATIONALISATION
# ─────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ─────────────────────────────────────────────
# FICHIERS STATIQUES & MÉDIAS
# ─────────────────────────────────────────────

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ─────────────────────────────────────────────
# DJANGO REST FRAMEWORK
# ─────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# ─────────────────────────────────────────────
# DRF SPECTACULAR (Swagger)
# ─────────────────────────────────────────────

SPECTACULAR_SETTINGS = {
    'TITLE': 'Score API',
    'DESCRIPTION': "Documentation de l'API du projet Score",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'Bearer': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}


# ─────────────────────────────────────────────
# SIMPLE JWT
# ─────────────────────────────────────────────

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ─────────────────────────────────────────────
# CACHE (Redis)
# ─────────────────────────────────────────────

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

DATA_TIMEOUT = 900
LOAN_REGISTER_TIMEOUT = 700


# ─────────────────────────────────────────────
# EMAIL
# ─────────────────────────────────────────────

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")


# ─────────────────────────────────────────────
# TOKEN DE SETUP COMPTE (AccountCredentials)
# ─────────────────────────────────────────────

SETUP_TOKEN_EXPIRY_MINUTES = 1440    # 24h
RESET_TOKEN_EXPIRY_MINUTES = 15      # 15 min


# ─────────────────────────────────────────────
# FRONTEND URL
# ─────────────────────────────────────────────

FRONTEND_URL = env('FRONTEND_URL')


# ─────────────────────────────────────────────
# CELERY
# ─────────────────────────────────────────────

CELERY_BROKER_URL                = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND            = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT            = ['json']
CELERY_TASK_SERIALIZER           = 'json'
CELERY_RESULT_SERIALIZER         = 'json'
CELERY_TIMEZONE                  = 'UTC'
CELERY_BEAT_SCHEDULER            = 'django_celery_beat.schedulers:DatabaseScheduler'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-subscriptions-daily': {
        'task':     'geography.tasks.check_subscriptions',
        'schedule': crontab(hour=0, minute=0),
    },
    'check-debt-deadlines-daily': {         # ✅ ajouté
        'task':     'customers.tasks.check_debt_deadlines',
        'schedule': crontab(hour=0, minute=0),
    },
}